name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          ref: main  # Replace with the default branch of your fork

      - name: Add Upstream Repo
        run: git remote add upstream https://github.com/kubernetes/kubernetes.git
        # Replace with the URL of the original repo

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Changes
        run: |
          git checkout main
          git merge upstream/master --allow-unrelated-histories -m "Sync with upstream"
          git push origin main
